[build]
base = "."
command = """\
       echo 'Running build command' && \
       npm run build\
       """
publish = "./build/"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[build.enviromnt]
REACT_APP_TEST = "test"